language: r
sudo: required

# Get mapshaper node module installed. Instructions from here:
# http://entulho.fiatjaf.alhur.es/guias/how-to-use-node-along-with-other-language-on-travis-ci/

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo add-apt-repository ppa:cran/v8
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libnode-dev libjq-dev
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mapshaper

r_packages:
  - jsonlite
  - devtools

r_github_packages:
  - jimhester/covr

after_success:
- R -e 'covr::codecov()'

r:
  - release
  - devel
  - oldrel

matrix:
  allow_failures:
    - r: devel

notifications:
  email:
    on_success: change
    on_failure: change
